---
- name: setup httpd
  hosts: server2
  tasks: 
   - name: use dnf to install httpd and firewalld
     dnf:
       name: 
       - httpd
       - firewalld
       state: latest 
       
   - name: use copy to generate index.html
     copy:
      dest: /var/www/html/index.html
      content: hello world in lab4
      
   - name: use service to activate httpd
     service:
      name: httpd
      state: started
      enabled: yes 
   - name: use service to activate firewalld
     service:
      name: firewalld
      state: started
      enabled: yes  

   - name: open ports in the firewall
     firewalld: 
      service: http
      state: enabled
      permanent: true
      immediate: true

